// relay.v1 defines the agent ↔ server contract.
//
// Direction of connection is the whole design: the agent DIALS OUT to the
// server and holds one bidirectional Session stream. The server never
// connects to a machine. The SDK/CLI path is HTTP/JSON (see
// internal/server/http.go), not this proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: relay/v1/agent.proto

package relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunState int32

const (
	RunState_RUN_STATE_UNSPECIFIED RunState = 0
	RunState_RUN_PENDING           RunState = 1 // queued on the server
	RunState_RUN_ASSIGNED          RunState = 2 // sent to an agent
	RunState_RUN_BUILDING          RunState = 3 // agent building/pulling the image
	RunState_RUN_RUNNING           RunState = 4
	RunState_RUN_SUCCEEDED         RunState = 5
	RunState_RUN_FAILED            RunState = 6 // user function raised (result blob has details)
	RunState_RUN_ERROR             RunState = 7 // infrastructure failure outside the function
	RunState_RUN_CANCELED          RunState = 8
	RunState_RUN_LOST              RunState = 9 // agent vanished while the run was live
)

// Enum value maps for RunState.
var (
	RunState_name = map[int32]string{
		0: "RUN_STATE_UNSPECIFIED",
		1: "RUN_PENDING",
		2: "RUN_ASSIGNED",
		3: "RUN_BUILDING",
		4: "RUN_RUNNING",
		5: "RUN_SUCCEEDED",
		6: "RUN_FAILED",
		7: "RUN_ERROR",
		8: "RUN_CANCELED",
		9: "RUN_LOST",
	}
	RunState_value = map[string]int32{
		"RUN_STATE_UNSPECIFIED": 0,
		"RUN_PENDING":           1,
		"RUN_ASSIGNED":          2,
		"RUN_BUILDING":          3,
		"RUN_RUNNING":           4,
		"RUN_SUCCEEDED":         5,
		"RUN_FAILED":            6,
		"RUN_ERROR":             7,
		"RUN_CANCELED":          8,
		"RUN_LOST":              9,
	}
)

func (x RunState) Enum() *RunState {
	p := new(RunState)
	*p = x
	return p
}

func (x RunState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunState) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_v1_agent_proto_enumTypes[0].Descriptor()
}

func (RunState) Type() protoreflect.EnumType {
	return &file_relay_v1_agent_proto_enumTypes[0]
}

func (x RunState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunState.Descriptor instead.
func (RunState) EnumDescriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{0}
}

type Accelerator struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Kind      string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`                             // "cuda" | "mps"
	MemoryMib uint64                 `protobuf:"varint,2,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"` // minimum per-device VRAM; 0 = any amount
	Count     uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// Exclusive requests require an otherwise-unreserved device and reserve
	// its complete capacity. Shared requests reserve memory_mib only.
	Exclusive     bool `protobuf:"varint,4,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accelerator) Reset() {
	*x = Accelerator{}
	mi := &file_relay_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accelerator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accelerator) ProtoMessage() {}

func (x *Accelerator) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accelerator.ProtoReflect.Descriptor instead.
func (*Accelerator) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Accelerator) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Accelerator) GetMemoryMib() uint64 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

func (x *Accelerator) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Accelerator) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

type Resources struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Cpus               float64                `protobuf:"fixed64,1,opt,name=cpus,proto3" json:"cpus,omitempty"`                                                     // 0 = unconstrained
	MemoryMib          uint64                 `protobuf:"varint,2,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"`                           // 0 = unconstrained
	AcceleratorOptions []*Accelerator         `protobuf:"bytes,3,rep,name=accelerator_options,json=acceleratorOptions,proto3" json:"accelerator_options,omitempty"` // any-of; empty = none needed
	TimeoutS           uint32                 `protobuf:"varint,4,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`                              // 0 = none
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_relay_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Resources) GetCpus() float64 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *Resources) GetMemoryMib() uint64 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

func (x *Resources) GetAcceleratorOptions() []*Accelerator {
	if x != nil {
		return x.AcceleratorOptions
	}
	return nil
}

func (x *Resources) GetTimeoutS() uint32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

type DetectedAccelerator struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Kind      string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`                             // "cuda" | "mps"
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                             // "NVIDIA GB10", "Apple M3 Max"
	MemoryMib uint64                 `protobuf:"varint,3,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"` // best-effort; see memory_unreliable
	Index     int32                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	// True on unified-memory parts (DGX Spark GB10, Apple Silicon) where the
	// driver cannot report a dedicated pool; memory_mib then mirrors system
	// memory and the scheduler must budget one shared pool.
	MemoryUnreliable bool `protobuf:"varint,5,opt,name=memory_unreliable,json=memoryUnreliable,proto3" json:"memory_unreliable,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DetectedAccelerator) Reset() {
	*x = DetectedAccelerator{}
	mi := &file_relay_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedAccelerator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedAccelerator) ProtoMessage() {}

func (x *DetectedAccelerator) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectedAccelerator.ProtoReflect.Descriptor instead.
func (*DetectedAccelerator) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *DetectedAccelerator) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DetectedAccelerator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetectedAccelerator) GetMemoryMib() uint64 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

func (x *DetectedAccelerator) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DetectedAccelerator) GetMemoryUnreliable() bool {
	if x != nil {
		return x.MemoryUnreliable
	}
	return false
}

type MachineInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`     // "linux" | "darwin"
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"` // "amd64" | "arm64"
	CpuCores      uint32                 `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMib     uint64                 `protobuf:"varint,5,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"`
	Accelerators  []*DetectedAccelerator `protobuf:"bytes,6,rep,name=accelerators,proto3" json:"accelerators,omitempty"`
	Executors     []string               `protobuf:"bytes,7,rep,name=executors,proto3" json:"executors,omitempty"` // "docker", "docker-cuda", "native-mps"
	UnifiedMemory bool                   `protobuf:"varint,8,opt,name=unified_memory,json=unifiedMemory,proto3" json:"unified_memory,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,9,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineInventory) Reset() {
	*x = MachineInventory{}
	mi := &file_relay_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInventory) ProtoMessage() {}

func (x *MachineInventory) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInventory.ProtoReflect.Descriptor instead.
func (*MachineInventory) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *MachineInventory) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MachineInventory) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *MachineInventory) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *MachineInventory) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *MachineInventory) GetMemoryMib() uint64 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

func (x *MachineInventory) GetAccelerators() []*DetectedAccelerator {
	if x != nil {
		return x.Accelerators
	}
	return nil
}

func (x *MachineInventory) GetExecutors() []string {
	if x != nil {
		return x.Executors
	}
	return nil
}

func (x *MachineInventory) GetUnifiedMemory() bool {
	if x != nil {
		return x.UnifiedMemory
	}
	return false
}

func (x *MachineInventory) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type RunSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunId           string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	App             string                 `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Function        string                 `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	EntryFile       string                 `protobuf:"bytes,4,opt,name=entry_file,json=entryFile,proto3" json:"entry_file,omitempty"`
	Resources       *Resources             `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	ImageTag        string                 `protobuf:"bytes,6,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`                      // content-addressed relay-img:<hash>
	ImageDockerfile string                 `protobuf:"bytes,7,opt,name=image_dockerfile,json=imageDockerfile,proto3" json:"image_dockerfile,omitempty"` // agent builds natively when tag is missing
	BundleSha256    string                 `protobuf:"bytes,8,opt,name=bundle_sha256,json=bundleSha256,proto3" json:"bundle_sha256,omitempty"`          // project tarball blob
	ArgsSha256      string                 `protobuf:"bytes,9,opt,name=args_sha256,json=argsSha256,proto3" json:"args_sha256,omitempty"`                // pickled-call blob
	RuntimeProtocol uint32                 `protobuf:"varint,10,opt,name=runtime_protocol,json=runtimeProtocol,proto3" json:"runtime_protocol,omitempty"`
	PythonMinor     string                 `protobuf:"bytes,11,opt,name=python_minor,json=pythonMinor,proto3" json:"python_minor,omitempty"` // client interpreter, e.g. "3.14"
	// Scheduler decision (M2+): which devices this run may use. Agents pin
	// containers to exactly these (DeviceRequests.DeviceIDs), never "all".
	AcceleratorKind string  `protobuf:"bytes,12,opt,name=accelerator_kind,json=acceleratorKind,proto3" json:"accelerator_kind,omitempty"` // "cuda" | "mps" | ""
	DeviceIndices   []int32 `protobuf:"varint,13,rep,packed,name=device_indices,json=deviceIndices,proto3" json:"device_indices,omitempty"`
	// Machine-local volumes: container mount path → volume name. Volumes
	// live under the agent state dir; data stays on the machine that wrote it.
	Volumes map[string]string `protobuf:"bytes,14,rep,name=volumes,proto3" json:"volumes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Secret NAMES only. Values never ride in a RunSpec because they would persist
	// on run rows). Agents fetch values via GetSecrets at run start.
	SecretNames []string `protobuf:"bytes,15,rep,name=secret_names,json=secretNames,proto3" json:"secret_names,omitempty"`
	// Services (M4): kind distinguishes one-shot jobs from supervised
	// long-running services.
	Kind        string `protobuf:"bytes,16,opt,name=kind,proto3" json:"kind,omitempty"`                                   // "" | "job" | "service"
	ServicePort uint32 `protobuf:"varint,17,opt,name=service_port,json=servicePort,proto3" json:"service_port,omitempty"` // container port the service listens on
	Expose      string `protobuf:"bytes,18,opt,name=expose,proto3" json:"expose,omitempty"`                               // "private" (LAN port) | "public" (tunnel)
	// Capability key for the public auth proxy; anonymous access requires the
	// user to have opted out explicitly (auth="none" → empty key + expose ok).
	ServiceKey      string `protobuf:"bytes,19,opt,name=service_key,json=serviceKey,proto3" json:"service_key,omitempty"`
	ServiceAuthNone bool   `protobuf:"varint,20,opt,name=service_auth_none,json=serviceAuthNone,proto3" json:"service_auth_none,omitempty"`
	// Native (containerless) execution info for MPS machines (M5). Only
	// pip-installable images qualify; apt/run/registry ops are Docker-only.
	NativeEnv     *NativeEnv `protobuf:"bytes,21,opt,name=native_env,json=nativeEnv,proto3" json:"native_env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSpec) Reset() {
	*x = RunSpec{}
	mi := &file_relay_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSpec) ProtoMessage() {}

func (x *RunSpec) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSpec.ProtoReflect.Descriptor instead.
func (*RunSpec) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RunSpec) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunSpec) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *RunSpec) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *RunSpec) GetEntryFile() string {
	if x != nil {
		return x.EntryFile
	}
	return ""
}

func (x *RunSpec) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *RunSpec) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *RunSpec) GetImageDockerfile() string {
	if x != nil {
		return x.ImageDockerfile
	}
	return ""
}

func (x *RunSpec) GetBundleSha256() string {
	if x != nil {
		return x.BundleSha256
	}
	return ""
}

func (x *RunSpec) GetArgsSha256() string {
	if x != nil {
		return x.ArgsSha256
	}
	return ""
}

func (x *RunSpec) GetRuntimeProtocol() uint32 {
	if x != nil {
		return x.RuntimeProtocol
	}
	return 0
}

func (x *RunSpec) GetPythonMinor() string {
	if x != nil {
		return x.PythonMinor
	}
	return ""
}

func (x *RunSpec) GetAcceleratorKind() string {
	if x != nil {
		return x.AcceleratorKind
	}
	return ""
}

func (x *RunSpec) GetDeviceIndices() []int32 {
	if x != nil {
		return x.DeviceIndices
	}
	return nil
}

func (x *RunSpec) GetVolumes() map[string]string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *RunSpec) GetSecretNames() []string {
	if x != nil {
		return x.SecretNames
	}
	return nil
}

func (x *RunSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RunSpec) GetServicePort() uint32 {
	if x != nil {
		return x.ServicePort
	}
	return 0
}

func (x *RunSpec) GetExpose() string {
	if x != nil {
		return x.Expose
	}
	return ""
}

func (x *RunSpec) GetServiceKey() string {
	if x != nil {
		return x.ServiceKey
	}
	return ""
}

func (x *RunSpec) GetServiceAuthNone() bool {
	if x != nil {
		return x.ServiceAuthNone
	}
	return false
}

func (x *RunSpec) GetNativeEnv() *NativeEnv {
	if x != nil {
		return x.NativeEnv
	}
	return nil
}

type NativeEnv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supported     bool                   `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`                                                              // false → never place on native executors
	PythonMinor   string                 `protobuf:"bytes,2,opt,name=python_minor,json=pythonMinor,proto3" json:"python_minor,omitempty"`                                        // interpreter to venv ("3.14")
	PipPackages   []string               `protobuf:"bytes,3,rep,name=pip_packages,json=pipPackages,proto3" json:"pip_packages,omitempty"`                                        // incl. the exact cloudpickle pin
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Image.env() vars
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NativeEnv) Reset() {
	*x = NativeEnv{}
	mi := &file_relay_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeEnv) ProtoMessage() {}

func (x *NativeEnv) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeEnv.ProtoReflect.Descriptor instead.
func (*NativeEnv) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *NativeEnv) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *NativeEnv) GetPythonMinor() string {
	if x != nil {
		return x.PythonMinor
	}
	return ""
}

func (x *NativeEnv) GetPipPackages() []string {
	if x != nil {
		return x.PipPackages
	}
	return nil
}

func (x *NativeEnv) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type SecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretsRequest) Reset() {
	*x = SecretsRequest{}
	mi := &file_relay_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretsRequest) ProtoMessage() {}

func (x *SecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretsRequest.ProtoReflect.Descriptor instead.
func (*SecretsRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SecretsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SecretsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretsResponse) Reset() {
	*x = SecretsResponse{}
	mi := &file_relay_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretsResponse) ProtoMessage() {}

func (x *SecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretsResponse.ProtoReflect.Descriptor instead.
func (*SecretsResponse) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SecretsResponse) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinToken     string                 `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	RequestedName string                 `protobuf:"bytes,2,opt,name=requested_name,json=requestedName,proto3" json:"requested_name,omitempty"` // "" = server derives from hostname
	Inventory     *MachineInventory      `protobuf:"bytes,3,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_relay_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterRequest) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *RegisterRequest) GetRequestedName() string {
	if x != nil {
		return x.RequestedName
	}
	return ""
}

func (x *RegisterRequest) GetInventory() *MachineInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	MachineName   string                 `protobuf:"bytes,2,opt,name=machine_name,json=machineName,proto3" json:"machine_name,omitempty"`
	AgentToken    string                 `protobuf:"bytes,3,opt,name=agent_token,json=agentToken,proto3" json:"agent_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_relay_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *RegisterResponse) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *RegisterResponse) GetAgentToken() string {
	if x != nil {
		return x.AgentToken
	}
	return ""
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_RunStatus
	//	*AgentMessage_Logs
	//	*AgentMessage_ExecOutput
	Msg           isAgentMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_relay_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *AgentMessage) GetMsg() isAgentMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMessage) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetRunStatus() *RunStatusUpdate {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_RunStatus); ok {
			return x.RunStatus
		}
	}
	return nil
}

func (x *AgentMessage) GetLogs() *LogBatch {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Logs); ok {
			return x.Logs
		}
	}
	return nil
}

func (x *AgentMessage) GetExecOutput() *ExecOutput {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_ExecOutput); ok {
			return x.ExecOutput
		}
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_RunStatus struct {
	RunStatus *RunStatusUpdate `protobuf:"bytes,3,opt,name=run_status,json=runStatus,proto3,oneof"`
}

type AgentMessage_Logs struct {
	Logs *LogBatch `protobuf:"bytes,4,opt,name=logs,proto3,oneof"`
}

type AgentMessage_ExecOutput struct {
	ExecOutput *ExecOutput `protobuf:"bytes,5,opt,name=exec_output,json=execOutput,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Msg() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Msg() {}

func (*AgentMessage_RunStatus) isAgentMessage_Msg() {}

func (*AgentMessage_Logs) isAgentMessage_Msg() {}

func (*AgentMessage_ExecOutput) isAgentMessage_Msg() {}

// Host-command execution (relay shell): bounded, non-interactive, output
// streamed back in chunks. There is no stdin or PTY. `relay shell spark nvidia-smi`
// territory, not a login shell (machines stay SSH-reachable for that).
type ExecOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // spawn failure etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_relay_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ExecOutput) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecOutput) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ExecOutput) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ExecOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AgentHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MachineId       string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Inventory       *MachineInventory      `protobuf:"bytes,2,opt,name=inventory,proto3" json:"inventory,omitempty"`
	CachedImageTags []string               `protobuf:"bytes,3,rep,name=cached_image_tags,json=cachedImageTags,proto3" json:"cached_image_tags,omitempty"` // scheduler locality input
	ActiveRunIds    []string               `protobuf:"bytes,4,rep,name=active_run_ids,json=activeRunIds,proto3" json:"active_run_ids,omitempty"`          // reconciliation after reconnect
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_relay_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *AgentHello) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *AgentHello) GetInventory() *MachineInventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *AgentHello) GetCachedImageTags() []string {
	if x != nil {
		return x.CachedImageTags
	}
	return nil
}

func (x *AgentHello) GetActiveRunIds() []string {
	if x != nil {
		return x.ActiveRunIds
	}
	return nil
}

type AcceleratorUsage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Index                int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	MemoryUsedMib        uint64                 `protobuf:"varint,2,opt,name=memory_used_mib,json=memoryUsedMib,proto3" json:"memory_used_mib,omitempty"`
	Utilization          float64                `protobuf:"fixed64,3,opt,name=utilization,proto3" json:"utilization,omitempty"` // 0..1, best-effort
	MemoryUsageAvailable bool                   `protobuf:"varint,4,opt,name=memory_usage_available,json=memoryUsageAvailable,proto3" json:"memory_usage_available,omitempty"`
	UtilizationAvailable bool                   `protobuf:"varint,5,opt,name=utilization_available,json=utilizationAvailable,proto3" json:"utilization_available,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AcceleratorUsage) Reset() {
	*x = AcceleratorUsage{}
	mi := &file_relay_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceleratorUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceleratorUsage) ProtoMessage() {}

func (x *AcceleratorUsage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceleratorUsage.ProtoReflect.Descriptor instead.
func (*AcceleratorUsage) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *AcceleratorUsage) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AcceleratorUsage) GetMemoryUsedMib() uint64 {
	if x != nil {
		return x.MemoryUsedMib
	}
	return 0
}

func (x *AcceleratorUsage) GetUtilization() float64 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

func (x *AcceleratorUsage) GetMemoryUsageAvailable() bool {
	if x != nil {
		return x.MemoryUsageAvailable
	}
	return false
}

func (x *AcceleratorUsage) GetUtilizationAvailable() bool {
	if x != nil {
		return x.UtilizationAvailable
	}
	return false
}

type Heartbeat struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CpuUsedCores         float64                `protobuf:"fixed64,1,opt,name=cpu_used_cores,json=cpuUsedCores,proto3" json:"cpu_used_cores,omitempty"`
	MemoryUsedMib        uint64                 `protobuf:"varint,2,opt,name=memory_used_mib,json=memoryUsedMib,proto3" json:"memory_used_mib,omitempty"`
	Accelerators         []*AcceleratorUsage    `protobuf:"bytes,3,rep,name=accelerators,proto3" json:"accelerators,omitempty"`
	DiskFreeMib          uint64                 `protobuf:"varint,4,opt,name=disk_free_mib,json=diskFreeMib,proto3" json:"disk_free_mib,omitempty"`
	DiskTotalMib         uint64                 `protobuf:"varint,5,opt,name=disk_total_mib,json=diskTotalMib,proto3" json:"disk_total_mib,omitempty"`
	SampledAtUnixMs      int64                  `protobuf:"varint,6,opt,name=sampled_at_unix_ms,json=sampledAtUnixMs,proto3" json:"sampled_at_unix_ms,omitempty"` // 0 = liveness heartbeat without telemetry
	CpuUsageAvailable    bool                   `protobuf:"varint,7,opt,name=cpu_usage_available,json=cpuUsageAvailable,proto3" json:"cpu_usage_available,omitempty"`
	MemoryUsageAvailable bool                   `protobuf:"varint,8,opt,name=memory_usage_available,json=memoryUsageAvailable,proto3" json:"memory_usage_available,omitempty"`
	DiskUsageAvailable   bool                   `protobuf:"varint,9,opt,name=disk_usage_available,json=diskUsageAvailable,proto3" json:"disk_usage_available,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_relay_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *Heartbeat) GetCpuUsedCores() float64 {
	if x != nil {
		return x.CpuUsedCores
	}
	return 0
}

func (x *Heartbeat) GetMemoryUsedMib() uint64 {
	if x != nil {
		return x.MemoryUsedMib
	}
	return 0
}

func (x *Heartbeat) GetAccelerators() []*AcceleratorUsage {
	if x != nil {
		return x.Accelerators
	}
	return nil
}

func (x *Heartbeat) GetDiskFreeMib() uint64 {
	if x != nil {
		return x.DiskFreeMib
	}
	return 0
}

func (x *Heartbeat) GetDiskTotalMib() uint64 {
	if x != nil {
		return x.DiskTotalMib
	}
	return 0
}

func (x *Heartbeat) GetSampledAtUnixMs() int64 {
	if x != nil {
		return x.SampledAtUnixMs
	}
	return 0
}

func (x *Heartbeat) GetCpuUsageAvailable() bool {
	if x != nil {
		return x.CpuUsageAvailable
	}
	return false
}

func (x *Heartbeat) GetMemoryUsageAvailable() bool {
	if x != nil {
		return x.MemoryUsageAvailable
	}
	return false
}

func (x *Heartbeat) GetDiskUsageAvailable() bool {
	if x != nil {
		return x.DiskUsageAvailable
	}
	return false
}

type RunStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	State         RunState               `protobuf:"varint,2,opt,name=state,proto3,enum=relay.v1.RunState" json:"state,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"` // human-readable ("pulling python:3.14-slim")
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ResultSha256  string                 `protobuf:"bytes,5,opt,name=result_sha256,json=resultSha256,proto3" json:"result_sha256,omitempty"` // set on SUCCEEDED / FAILED
	Endpoint      string                 `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                             // services: where it is reachable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStatusUpdate) Reset() {
	*x = RunStatusUpdate{}
	mi := &file_relay_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStatusUpdate) ProtoMessage() {}

func (x *RunStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStatusUpdate.ProtoReflect.Descriptor instead.
func (*RunStatusUpdate) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *RunStatusUpdate) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunStatusUpdate) GetState() RunState {
	if x != nil {
		return x.State
	}
	return RunState_RUN_STATE_UNSPECIFIED
}

func (x *RunStatusUpdate) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *RunStatusUpdate) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunStatusUpdate) GetResultSha256() string {
	if x != nil {
		return x.ResultSha256
	}
	return ""
}

func (x *RunStatusUpdate) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnixMs      int64                  `protobuf:"varint,1,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Stderr        bool                   `protobuf:"varint,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_relay_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *LogLine) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogLine) GetStderr() bool {
	if x != nil {
		return x.Stderr
	}
	return false
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Lines         []*LogLine             `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_relay_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *LogBatch) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *LogBatch) GetLines() []*LogLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_Hello
	//	*ServerMessage_Assign
	//	*ServerMessage_Cancel
	//	*ServerMessage_Exec
	//	*ServerMessage_Telemetry
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_relay_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetHello() *ServerHello {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ServerMessage) GetAssign() *RunAssignment {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Assign); ok {
			return x.Assign
		}
	}
	return nil
}

func (x *ServerMessage) GetCancel() *CancelRun {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ServerMessage) GetExec() *ExecRequest {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *ServerMessage) GetTelemetry() *TelemetryRequest {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Telemetry); ok {
			return x.Telemetry
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_Hello struct {
	Hello *ServerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ServerMessage_Assign struct {
	Assign *RunAssignment `protobuf:"bytes,2,opt,name=assign,proto3,oneof"`
}

type ServerMessage_Cancel struct {
	Cancel *CancelRun `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

type ServerMessage_Exec struct {
	Exec *ExecRequest `protobuf:"bytes,4,opt,name=exec,proto3,oneof"`
}

type ServerMessage_Telemetry struct {
	Telemetry *TelemetryRequest `protobuf:"bytes,5,opt,name=telemetry,proto3,oneof"`
}

func (*ServerMessage_Hello) isServerMessage_Msg() {}

func (*ServerMessage_Assign) isServerMessage_Msg() {}

func (*ServerMessage_Cancel) isServerMessage_Msg() {}

func (*ServerMessage_Exec) isServerMessage_Msg() {}

func (*ServerMessage_Telemetry) isServerMessage_Msg() {}

// A short lease keeps host monitoring demand-driven. The dashboard renews it
// while the Machines page is visible; the agent stops sampling on expiry.
type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationS     uint32                 `protobuf:"varint,1,opt,name=duration_s,json=durationS,proto3" json:"duration_s,omitempty"`
	IntervalS     uint32                 `protobuf:"varint,2,opt,name=interval_s,json=intervalS,proto3" json:"interval_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_relay_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *TelemetryRequest) GetDurationS() uint32 {
	if x != nil {
		return x.DurationS
	}
	return 0
}

func (x *TelemetryRequest) GetIntervalS() uint32 {
	if x != nil {
		return x.IntervalS
	}
	return 0
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Argv          []string               `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty"`
	TimeoutS      uint32                 `protobuf:"varint,3,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_relay_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ExecRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ExecRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ExecRequest) GetTimeoutS() uint32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

type ServerHello struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerVersion      string                 `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	HeartbeatIntervalS uint32                 `protobuf:"varint,2,opt,name=heartbeat_interval_s,json=heartbeatIntervalS,proto3" json:"heartbeat_interval_s,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_relay_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ServerHello) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *ServerHello) GetHeartbeatIntervalS() uint32 {
	if x != nil {
		return x.HeartbeatIntervalS
	}
	return 0
}

type RunAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *RunSpec               `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAssignment) Reset() {
	*x = RunAssignment{}
	mi := &file_relay_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAssignment) ProtoMessage() {}

func (x *RunAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAssignment.ProtoReflect.Descriptor instead.
func (*RunAssignment) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *RunAssignment) GetSpec() *RunSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CancelRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRun) Reset() {
	*x = CancelRun{}
	mi := &file_relay_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRun) ProtoMessage() {}

func (x *CancelRun) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRun.ProtoReflect.Descriptor instead.
func (*CancelRun) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *CancelRun) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type BlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobRequest) Reset() {
	*x = BlobRequest{}
	mi := &file_relay_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobRequest) ProtoMessage() {}

func (x *BlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobRequest.ProtoReflect.Descriptor instead.
func (*BlobRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *BlobRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type BlobChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"` // set on the first chunk
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobChunk) Reset() {
	*x = BlobChunk{}
	mi := &file_relay_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobChunk) ProtoMessage() {}

func (x *BlobChunk) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobChunk.ProtoReflect.Descriptor instead.
func (*BlobChunk) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{25}
}

func (x *BlobChunk) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *BlobChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlobStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobStat) Reset() {
	*x = BlobStat{}
	mi := &file_relay_v1_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobStat) ProtoMessage() {}

func (x *BlobStat) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobStat.ProtoReflect.Descriptor instead.
func (*BlobStat) Descriptor() ([]byte, []int) {
	return file_relay_v1_agent_proto_rawDescGZIP(), []int{26}
}

func (x *BlobStat) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *BlobStat) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *BlobStat) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_relay_v1_agent_proto protoreflect.FileDescriptor

const file_relay_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14relay/v1/agent.proto\x12\brelay.v1\"t\n" +
	"\vAccelerator\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\x02 \x01(\x04R\tmemoryMib\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x1c\n" +
	"\texclusive\x18\x04 \x01(\bR\texclusive\"\xa3\x01\n" +
	"\tResources\x12\x12\n" +
	"\x04cpus\x18\x01 \x01(\x01R\x04cpus\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\x02 \x01(\x04R\tmemoryMib\x12F\n" +
	"\x13accelerator_options\x18\x03 \x03(\v2\x15.relay.v1.AcceleratorR\x12acceleratorOptions\x12\x1b\n" +
	"\ttimeout_s\x18\x04 \x01(\rR\btimeoutS\"\x9f\x01\n" +
	"\x13DetectedAccelerator\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\x03 \x01(\x04R\tmemoryMib\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05index\x12+\n" +
	"\x11memory_unreliable\x18\x05 \x01(\bR\x10memoryUnreliable\"\xbb\x02\n" +
	"\x10MachineInventory\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\rR\bcpuCores\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\x05 \x01(\x04R\tmemoryMib\x12A\n" +
	"\faccelerators\x18\x06 \x03(\v2\x1d.relay.v1.DetectedAcceleratorR\faccelerators\x12\x1c\n" +
	"\texecutors\x18\a \x03(\tR\texecutors\x12%\n" +
	"\x0eunified_memory\x18\b \x01(\bR\runifiedMemory\x12#\n" +
	"\ragent_version\x18\t \x01(\tR\fagentVersion\"\xb7\x06\n" +
	"\aRunSpec\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x10\n" +
	"\x03app\x18\x02 \x01(\tR\x03app\x12\x1a\n" +
	"\bfunction\x18\x03 \x01(\tR\bfunction\x12\x1d\n" +
	"\n" +
	"entry_file\x18\x04 \x01(\tR\tentryFile\x121\n" +
	"\tresources\x18\x05 \x01(\v2\x13.relay.v1.ResourcesR\tresources\x12\x1b\n" +
	"\timage_tag\x18\x06 \x01(\tR\bimageTag\x12)\n" +
	"\x10image_dockerfile\x18\a \x01(\tR\x0fimageDockerfile\x12#\n" +
	"\rbundle_sha256\x18\b \x01(\tR\fbundleSha256\x12\x1f\n" +
	"\vargs_sha256\x18\t \x01(\tR\n" +
	"argsSha256\x12)\n" +
	"\x10runtime_protocol\x18\n" +
	" \x01(\rR\x0fruntimeProtocol\x12!\n" +
	"\fpython_minor\x18\v \x01(\tR\vpythonMinor\x12)\n" +
	"\x10accelerator_kind\x18\f \x01(\tR\x0facceleratorKind\x12%\n" +
	"\x0edevice_indices\x18\r \x03(\x05R\rdeviceIndices\x128\n" +
	"\avolumes\x18\x0e \x03(\v2\x1e.relay.v1.RunSpec.VolumesEntryR\avolumes\x12!\n" +
	"\fsecret_names\x18\x0f \x03(\tR\vsecretNames\x12\x12\n" +
	"\x04kind\x18\x10 \x01(\tR\x04kind\x12!\n" +
	"\fservice_port\x18\x11 \x01(\rR\vservicePort\x12\x16\n" +
	"\x06expose\x18\x12 \x01(\tR\x06expose\x12\x1f\n" +
	"\vservice_key\x18\x13 \x01(\tR\n" +
	"serviceKey\x12*\n" +
	"\x11service_auth_none\x18\x14 \x01(\bR\x0fserviceAuthNone\x122\n" +
	"\n" +
	"native_env\x18\x15 \x01(\v2\x13.relay.v1.NativeEnvR\tnativeEnv\x1a:\n" +
	"\fVolumesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x01\n" +
	"\tNativeEnv\x12\x1c\n" +
	"\tsupported\x18\x01 \x01(\bR\tsupported\x12!\n" +
	"\fpython_minor\x18\x02 \x01(\tR\vpythonMinor\x12!\n" +
	"\fpip_packages\x18\x03 \x03(\tR\vpipPackages\x12.\n" +
	"\x03env\x18\x04 \x03(\v2\x1c.relay.v1.NativeEnv.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x0eSecretsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\"\x8b\x01\n" +
	"\x0fSecretsResponse\x12=\n" +
	"\x06values\x18\x01 \x03(\v2%.relay.v1.SecretsResponse.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"join_token\x18\x01 \x01(\tR\tjoinToken\x12%\n" +
	"\x0erequested_name\x18\x02 \x01(\tR\rrequestedName\x128\n" +
	"\tinventory\x18\x03 \x01(\v2\x1a.relay.v1.MachineInventoryR\tinventory\"u\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12!\n" +
	"\fmachine_name\x18\x02 \x01(\tR\vmachineName\x12\x1f\n" +
	"\vagent_token\x18\x03 \x01(\tR\n" +
	"agentToken\"\x97\x02\n" +
	"\fAgentMessage\x12,\n" +
	"\x05hello\x18\x01 \x01(\v2\x14.relay.v1.AgentHelloH\x00R\x05hello\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x13.relay.v1.HeartbeatH\x00R\theartbeat\x12:\n" +
	"\n" +
	"run_status\x18\x03 \x01(\v2\x19.relay.v1.RunStatusUpdateH\x00R\trunStatus\x12(\n" +
	"\x04logs\x18\x04 \x01(\v2\x12.relay.v1.LogBatchH\x00R\x04logs\x127\n" +
	"\vexec_output\x18\x05 \x01(\v2\x14.relay.v1.ExecOutputH\x00R\n" +
	"execOutputB\x05\n" +
	"\x03msg\"\x82\x01\n" +
	"\n" +
	"ExecOutput\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xb7\x01\n" +
	"\n" +
	"AgentHello\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x128\n" +
	"\tinventory\x18\x02 \x01(\v2\x1a.relay.v1.MachineInventoryR\tinventory\x12*\n" +
	"\x11cached_image_tags\x18\x03 \x03(\tR\x0fcachedImageTags\x12$\n" +
	"\x0eactive_run_ids\x18\x04 \x03(\tR\factiveRunIds\"\xdd\x01\n" +
	"\x10AcceleratorUsage\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12&\n" +
	"\x0fmemory_used_mib\x18\x02 \x01(\x04R\rmemoryUsedMib\x12 \n" +
	"\vutilization\x18\x03 \x01(\x01R\vutilization\x124\n" +
	"\x16memory_usage_available\x18\x04 \x01(\bR\x14memoryUsageAvailable\x123\n" +
	"\x15utilization_available\x18\x05 \x01(\bR\x14utilizationAvailable\"\xa8\x03\n" +
	"\tHeartbeat\x12$\n" +
	"\x0ecpu_used_cores\x18\x01 \x01(\x01R\fcpuUsedCores\x12&\n" +
	"\x0fmemory_used_mib\x18\x02 \x01(\x04R\rmemoryUsedMib\x12>\n" +
	"\faccelerators\x18\x03 \x03(\v2\x1a.relay.v1.AcceleratorUsageR\faccelerators\x12\"\n" +
	"\rdisk_free_mib\x18\x04 \x01(\x04R\vdiskFreeMib\x12$\n" +
	"\x0edisk_total_mib\x18\x05 \x01(\x04R\fdiskTotalMib\x12+\n" +
	"\x12sampled_at_unix_ms\x18\x06 \x01(\x03R\x0fsampledAtUnixMs\x12.\n" +
	"\x13cpu_usage_available\x18\a \x01(\bR\x11cpuUsageAvailable\x124\n" +
	"\x16memory_usage_available\x18\b \x01(\bR\x14memoryUsageAvailable\x120\n" +
	"\x14disk_usage_available\x18\t \x01(\bR\x12diskUsageAvailable\"\xc8\x01\n" +
	"\x0fRunStatusUpdate\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12(\n" +
	"\x05state\x18\x02 \x01(\x0e2\x12.relay.v1.RunStateR\x05state\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12#\n" +
	"\rresult_sha256\x18\x05 \x01(\tR\fresultSha256\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\"S\n" +
	"\aLogLine\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x01 \x01(\x03R\btsUnixMs\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\bR\x06stderr\"J\n" +
	"\bLogBatch\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12'\n" +
	"\x05lines\x18\x02 \x03(\v2\x11.relay.v1.LogLineR\x05lines\"\x90\x02\n" +
	"\rServerMessage\x12-\n" +
	"\x05hello\x18\x01 \x01(\v2\x15.relay.v1.ServerHelloH\x00R\x05hello\x121\n" +
	"\x06assign\x18\x02 \x01(\v2\x17.relay.v1.RunAssignmentH\x00R\x06assign\x12-\n" +
	"\x06cancel\x18\x03 \x01(\v2\x13.relay.v1.CancelRunH\x00R\x06cancel\x12+\n" +
	"\x04exec\x18\x04 \x01(\v2\x15.relay.v1.ExecRequestH\x00R\x04exec\x12:\n" +
	"\ttelemetry\x18\x05 \x01(\v2\x1a.relay.v1.TelemetryRequestH\x00R\ttelemetryB\x05\n" +
	"\x03msg\"P\n" +
	"\x10TelemetryRequest\x12\x1d\n" +
	"\n" +
	"duration_s\x18\x01 \x01(\rR\tdurationS\x12\x1d\n" +
	"\n" +
	"interval_s\x18\x02 \x01(\rR\tintervalS\"W\n" +
	"\vExecRequest\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x12\n" +
	"\x04argv\x18\x02 \x03(\tR\x04argv\x12\x1b\n" +
	"\ttimeout_s\x18\x03 \x01(\rR\btimeoutS\"f\n" +
	"\vServerHello\x12%\n" +
	"\x0eserver_version\x18\x01 \x01(\tR\rserverVersion\x120\n" +
	"\x14heartbeat_interval_s\x18\x02 \x01(\rR\x12heartbeatIntervalS\"6\n" +
	"\rRunAssignment\x12%\n" +
	"\x04spec\x18\x01 \x01(\v2\x11.relay.v1.RunSpecR\x04spec\"\"\n" +
	"\tCancelRun\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"%\n" +
	"\vBlobRequest\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\"7\n" +
	"\tBlobChunk\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"N\n" +
	"\bBlobStat\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size*\xbd\x01\n" +
	"\bRunState\x12\x19\n" +
	"\x15RUN_STATE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vRUN_PENDING\x10\x01\x12\x10\n" +
	"\fRUN_ASSIGNED\x10\x02\x12\x10\n" +
	"\fRUN_BUILDING\x10\x03\x12\x0f\n" +
	"\vRUN_RUNNING\x10\x04\x12\x11\n" +
	"\rRUN_SUCCEEDED\x10\x05\x12\x0e\n" +
	"\n" +
	"RUN_FAILED\x10\x06\x12\r\n" +
	"\tRUN_ERROR\x10\a\x12\x10\n" +
	"\fRUN_CANCELED\x10\b\x12\f\n" +
	"\bRUN_LOST\x10\t2\x81\x03\n" +
	"\fAgentService\x12A\n" +
	"\bRegister\x12\x19.relay.v1.RegisterRequest\x1a\x1a.relay.v1.RegisterResponse\x12>\n" +
	"\aSession\x12\x16.relay.v1.AgentMessage\x1a\x17.relay.v1.ServerMessage(\x010\x01\x124\n" +
	"\aHasBlob\x12\x15.relay.v1.BlobRequest\x1a\x12.relay.v1.BlobStat\x12<\n" +
	"\fDownloadBlob\x12\x15.relay.v1.BlobRequest\x1a\x13.relay.v1.BlobChunk0\x01\x127\n" +
	"\n" +
	"UploadBlob\x12\x13.relay.v1.BlobChunk\x1a\x12.relay.v1.BlobStat(\x01\x12A\n" +
	"\n" +
	"GetSecrets\x12\x18.relay.v1.SecretsRequest\x1a\x19.relay.v1.SecretsResponseBEZCgithub.com/matteomarolt/relay/relayd/internal/proto/relayv1;relayv1b\x06proto3"

var (
	file_relay_v1_agent_proto_rawDescOnce sync.Once
	file_relay_v1_agent_proto_rawDescData []byte
)

func file_relay_v1_agent_proto_rawDescGZIP() []byte {
	file_relay_v1_agent_proto_rawDescOnce.Do(func() {
		file_relay_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_v1_agent_proto_rawDesc), len(file_relay_v1_agent_proto_rawDesc)))
	})
	return file_relay_v1_agent_proto_rawDescData
}

var file_relay_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relay_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_relay_v1_agent_proto_goTypes = []any{
	(RunState)(0),               // 0: relay.v1.RunState
	(*Accelerator)(nil),         // 1: relay.v1.Accelerator
	(*Resources)(nil),           // 2: relay.v1.Resources
	(*DetectedAccelerator)(nil), // 3: relay.v1.DetectedAccelerator
	(*MachineInventory)(nil),    // 4: relay.v1.MachineInventory
	(*RunSpec)(nil),             // 5: relay.v1.RunSpec
	(*NativeEnv)(nil),           // 6: relay.v1.NativeEnv
	(*SecretsRequest)(nil),      // 7: relay.v1.SecretsRequest
	(*SecretsResponse)(nil),     // 8: relay.v1.SecretsResponse
	(*RegisterRequest)(nil),     // 9: relay.v1.RegisterRequest
	(*RegisterResponse)(nil),    // 10: relay.v1.RegisterResponse
	(*AgentMessage)(nil),        // 11: relay.v1.AgentMessage
	(*ExecOutput)(nil),          // 12: relay.v1.ExecOutput
	(*AgentHello)(nil),          // 13: relay.v1.AgentHello
	(*AcceleratorUsage)(nil),    // 14: relay.v1.AcceleratorUsage
	(*Heartbeat)(nil),           // 15: relay.v1.Heartbeat
	(*RunStatusUpdate)(nil),     // 16: relay.v1.RunStatusUpdate
	(*LogLine)(nil),             // 17: relay.v1.LogLine
	(*LogBatch)(nil),            // 18: relay.v1.LogBatch
	(*ServerMessage)(nil),       // 19: relay.v1.ServerMessage
	(*TelemetryRequest)(nil),    // 20: relay.v1.TelemetryRequest
	(*ExecRequest)(nil),         // 21: relay.v1.ExecRequest
	(*ServerHello)(nil),         // 22: relay.v1.ServerHello
	(*RunAssignment)(nil),       // 23: relay.v1.RunAssignment
	(*CancelRun)(nil),           // 24: relay.v1.CancelRun
	(*BlobRequest)(nil),         // 25: relay.v1.BlobRequest
	(*BlobChunk)(nil),           // 26: relay.v1.BlobChunk
	(*BlobStat)(nil),            // 27: relay.v1.BlobStat
	nil,                         // 28: relay.v1.RunSpec.VolumesEntry
	nil,                         // 29: relay.v1.NativeEnv.EnvEntry
	nil,                         // 30: relay.v1.SecretsResponse.ValuesEntry
}
var file_relay_v1_agent_proto_depIdxs = []int32{
	1,  // 0: relay.v1.Resources.accelerator_options:type_name -> relay.v1.Accelerator
	3,  // 1: relay.v1.MachineInventory.accelerators:type_name -> relay.v1.DetectedAccelerator
	2,  // 2: relay.v1.RunSpec.resources:type_name -> relay.v1.Resources
	28, // 3: relay.v1.RunSpec.volumes:type_name -> relay.v1.RunSpec.VolumesEntry
	6,  // 4: relay.v1.RunSpec.native_env:type_name -> relay.v1.NativeEnv
	29, // 5: relay.v1.NativeEnv.env:type_name -> relay.v1.NativeEnv.EnvEntry
	30, // 6: relay.v1.SecretsResponse.values:type_name -> relay.v1.SecretsResponse.ValuesEntry
	4,  // 7: relay.v1.RegisterRequest.inventory:type_name -> relay.v1.MachineInventory
	13, // 8: relay.v1.AgentMessage.hello:type_name -> relay.v1.AgentHello
	15, // 9: relay.v1.AgentMessage.heartbeat:type_name -> relay.v1.Heartbeat
	16, // 10: relay.v1.AgentMessage.run_status:type_name -> relay.v1.RunStatusUpdate
	18, // 11: relay.v1.AgentMessage.logs:type_name -> relay.v1.LogBatch
	12, // 12: relay.v1.AgentMessage.exec_output:type_name -> relay.v1.ExecOutput
	4,  // 13: relay.v1.AgentHello.inventory:type_name -> relay.v1.MachineInventory
	14, // 14: relay.v1.Heartbeat.accelerators:type_name -> relay.v1.AcceleratorUsage
	0,  // 15: relay.v1.RunStatusUpdate.state:type_name -> relay.v1.RunState
	17, // 16: relay.v1.LogBatch.lines:type_name -> relay.v1.LogLine
	22, // 17: relay.v1.ServerMessage.hello:type_name -> relay.v1.ServerHello
	23, // 18: relay.v1.ServerMessage.assign:type_name -> relay.v1.RunAssignment
	24, // 19: relay.v1.ServerMessage.cancel:type_name -> relay.v1.CancelRun
	21, // 20: relay.v1.ServerMessage.exec:type_name -> relay.v1.ExecRequest
	20, // 21: relay.v1.ServerMessage.telemetry:type_name -> relay.v1.TelemetryRequest
	5,  // 22: relay.v1.RunAssignment.spec:type_name -> relay.v1.RunSpec
	9,  // 23: relay.v1.AgentService.Register:input_type -> relay.v1.RegisterRequest
	11, // 24: relay.v1.AgentService.Session:input_type -> relay.v1.AgentMessage
	25, // 25: relay.v1.AgentService.HasBlob:input_type -> relay.v1.BlobRequest
	25, // 26: relay.v1.AgentService.DownloadBlob:input_type -> relay.v1.BlobRequest
	26, // 27: relay.v1.AgentService.UploadBlob:input_type -> relay.v1.BlobChunk
	7,  // 28: relay.v1.AgentService.GetSecrets:input_type -> relay.v1.SecretsRequest
	10, // 29: relay.v1.AgentService.Register:output_type -> relay.v1.RegisterResponse
	19, // 30: relay.v1.AgentService.Session:output_type -> relay.v1.ServerMessage
	27, // 31: relay.v1.AgentService.HasBlob:output_type -> relay.v1.BlobStat
	26, // 32: relay.v1.AgentService.DownloadBlob:output_type -> relay.v1.BlobChunk
	27, // 33: relay.v1.AgentService.UploadBlob:output_type -> relay.v1.BlobStat
	8,  // 34: relay.v1.AgentService.GetSecrets:output_type -> relay.v1.SecretsResponse
	29, // [29:35] is the sub-list for method output_type
	23, // [23:29] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_relay_v1_agent_proto_init() }
func file_relay_v1_agent_proto_init() {
	if File_relay_v1_agent_proto != nil {
		return
	}
	file_relay_v1_agent_proto_msgTypes[10].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_RunStatus)(nil),
		(*AgentMessage_Logs)(nil),
		(*AgentMessage_ExecOutput)(nil),
	}
	file_relay_v1_agent_proto_msgTypes[18].OneofWrappers = []any{
		(*ServerMessage_Hello)(nil),
		(*ServerMessage_Assign)(nil),
		(*ServerMessage_Cancel)(nil),
		(*ServerMessage_Exec)(nil),
		(*ServerMessage_Telemetry)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_v1_agent_proto_rawDesc), len(file_relay_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relay_v1_agent_proto_goTypes,
		DependencyIndexes: file_relay_v1_agent_proto_depIdxs,
		EnumInfos:         file_relay_v1_agent_proto_enumTypes,
		MessageInfos:      file_relay_v1_agent_proto_msgTypes,
	}.Build()
	File_relay_v1_agent_proto = out.File
	file_relay_v1_agent_proto_goTypes = nil
	file_relay_v1_agent_proto_depIdxs = nil
}
