// relay.v1 defines the agent ↔ server contract.
//
// Direction of connection is the whole design: the agent DIALS OUT to the
// server and holds one bidirectional Session stream. The server never
// connects to a machine. The SDK/CLI path is HTTP/JSON (see
// internal/server/http.go), not this proto.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: relay/v1/agent.proto

package relayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Register_FullMethodName     = "/relay.v1.AgentService/Register"
	AgentService_Session_FullMethodName      = "/relay.v1.AgentService/Session"
	AgentService_HasBlob_FullMethodName      = "/relay.v1.AgentService/HasBlob"
	AgentService_DownloadBlob_FullMethodName = "/relay.v1.AgentService/DownloadBlob"
	AgentService_UploadBlob_FullMethodName   = "/relay.v1.AgentService/UploadBlob"
	AgentService_GetSecrets_FullMethodName   = "/relay.v1.AgentService/GetSecrets"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Exchange a one-time join token for machine credentials.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// The long-lived control stream. Agent speaks first with Hello.
	// Authenticated with the agent token as a bearer credential in metadata.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
	HasBlob(ctx context.Context, in *BlobRequest, opts ...grpc.CallOption) (*BlobStat, error)
	DownloadBlob(ctx context.Context, in *BlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlobChunk], error)
	UploadBlob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BlobChunk, BlobStat], error)
	// Secret values for a run this machine was assigned. The server only
	// releases names referenced by the calling machine's active runs.
	GetSecrets(ctx context.Context, in *SecretsRequest, opts ...grpc.CallOption) (*SecretsResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AgentService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SessionClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

func (c *agentServiceClient) HasBlob(ctx context.Context, in *BlobRequest, opts ...grpc.CallOption) (*BlobStat, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlobStat)
	err := c.cc.Invoke(ctx, AgentService_HasBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DownloadBlob(ctx context.Context, in *BlobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlobChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_DownloadBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BlobRequest, BlobChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_DownloadBlobClient = grpc.ServerStreamingClient[BlobChunk]

func (c *agentServiceClient) UploadBlob(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BlobChunk, BlobStat], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], AgentService_UploadBlob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BlobChunk, BlobStat]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_UploadBlobClient = grpc.ClientStreamingClient[BlobChunk, BlobStat]

func (c *agentServiceClient) GetSecrets(ctx context.Context, in *SecretsRequest, opts ...grpc.CallOption) (*SecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretsResponse)
	err := c.cc.Invoke(ctx, AgentService_GetSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	// Exchange a one-time join token for machine credentials.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// The long-lived control stream. Agent speaks first with Hello.
	// Authenticated with the agent token as a bearer credential in metadata.
	Session(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	HasBlob(context.Context, *BlobRequest) (*BlobStat, error)
	DownloadBlob(*BlobRequest, grpc.ServerStreamingServer[BlobChunk]) error
	UploadBlob(grpc.ClientStreamingServer[BlobChunk, BlobStat]) error
	// Secret values for a run this machine was assigned. The server only
	// releases names referenced by the calling machine's active runs.
	GetSecrets(context.Context, *SecretsRequest) (*SecretsResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentServiceServer) Session(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedAgentServiceServer) HasBlob(context.Context, *BlobRequest) (*BlobStat, error) {
	return nil, status.Error(codes.Unimplemented, "method HasBlob not implemented")
}
func (UnimplementedAgentServiceServer) DownloadBlob(*BlobRequest, grpc.ServerStreamingServer[BlobChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadBlob not implemented")
}
func (UnimplementedAgentServiceServer) UploadBlob(grpc.ClientStreamingServer[BlobChunk, BlobStat]) error {
	return status.Error(codes.Unimplemented, "method UploadBlob not implemented")
}
func (UnimplementedAgentServiceServer) GetSecrets(context.Context, *SecretsRequest) (*SecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecrets not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Session(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SessionServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

func _AgentService_HasBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).HasBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_HasBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).HasBlob(ctx, req.(*BlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DownloadBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).DownloadBlob(m, &grpc.GenericServerStream[BlobRequest, BlobChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_DownloadBlobServer = grpc.ServerStreamingServer[BlobChunk]

func _AgentService_UploadBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).UploadBlob(&grpc.GenericServerStream[BlobChunk, BlobStat]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_UploadBlobServer = grpc.ClientStreamingServer[BlobChunk, BlobStat]

func _AgentService_GetSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetSecrets(ctx, req.(*SecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relay.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentService_Register_Handler,
		},
		{
			MethodName: "HasBlob",
			Handler:    _AgentService_HasBlob_Handler,
		},
		{
			MethodName: "GetSecrets",
			Handler:    _AgentService_GetSecrets_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _AgentService_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadBlob",
			Handler:       _AgentService_DownloadBlob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadBlob",
			Handler:       _AgentService_UploadBlob_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "relay/v1/agent.proto",
}
